name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  a-1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Ip confirm
        run: ifconfig | grep 192.168

      - name: Ip confirm
        run: |
          echo Job a-1
          sleep 180
  a-2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Ip confirm
        run: ifconfig | grep 192.168

      - name: Ip confirm
        run: |
          echo Job a-2
          sleep 180
